### ISSUE TITLE
Problem with convert to open3D

### ISSUE THREAD

**Issue by pangchunhei** [kekeblom/StrayVisualizer#16]
Hi, I am very new to open 3D and iOS programming. And I encounter a problem with the convert to open 3D program. I was able to run the program without any problem, but after it said done, I saw that that depth folder was empty. So I copied from the original raw data depth folder directly, but when I ran the 3D reconstruction, I was unable to run it. I show the following error:

I suspect the error is due to the size different between the image RGB and the depth data, but I am not sure? May I know many recommendations on the fix or other ways to import those data into open 3d?

OpenCV is detected. Using ORB + 5pt algorithm
making fragments from RGBD sequence.
Fragment 000 / 019 :: RGBD matching between frame : 0 and 1
[Open3D Error] (class std::shared_ptr<class open3d::geometry::RGBDImage> __cdecl open3d::geometry::RGBDImage::CreateFromColorAndDepth(const class open3d::geometry::Image &,const class open3d::geometry::Image &,double,double,bool)) D:\a\Open3D\Open3D\cpp\open3d\geometry\RGBDImageFactory.cpp:40: Unsupported image format.

Traceback (most recent call last):
  File "C:\Users\elsto\Documents\GitHub\CityU-FYP-Metaversa-3DModel\Trial\Open3D-0.16.0\examples\python\reconstruction_system\run_system.py", line 130, in <module>
    make_fragments.run(config)
  File "C:\Users\elsto\Documents\GitHub\CityU-FYP-Metaversa-3DModel\Trial\Open3D-0.16.0\examples\python\reconstruction_system\make_fragments.py", line 203, in run
    process_single_fragment(fragment_id, color_files, depth_files,
  File "C:\Users\elsto\Documents\GitHub\CityU-FYP-Metaversa-3DModel\Trial\Open3D-0.16.0\examples\python\reconstruction_system\make_fragments.py", line 174, in process_single_fragment
    make_posegraph_for_fragment(config["path_dataset"], sid, eid, color_files,
  File "C:\Users\elsto\Documents\GitHub\CityU-FYP-Metaversa-3DModel\Trial\Open3D-0.16.0\examples\python\reconstruction_system\make_fragments.py", line 94, in make_posegraph_for_fragment
    info] = register_one_rgbd_pair(s, t, color_files, depth_files,
  File "C:\Users\elsto\Documents\GitHub\CityU-FYP-Metaversa-3DModel\Trial\Open3D-0.16.0\examples\python\reconstruction_system\make_fragments.py", line 50, in register_one_rgbd_pair
    source_rgbd_image = read_rgbd_image(color_files[s], depth_files[s], True,
  File "C:\Users\elsto\Documents\GitHub\CityU-FYP-Metaversa-3DModel\Trial\Open3D-0.16.0\examples\python\open3d_example.py", line 213, in read_rgbd_image
    rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
RuntimeError: [Open3D Error] (class std::shared_ptr<class open3d::geometry::RGBDImage> __cdecl open3d::geometry::RGBDImage::CreateFromColorAndDepth(const class open3d::geometry::Image &,const class open3d::geometry::Image &,double,double,bool)) D:\a\Open3D\Open3D\cpp\open3d\geometry\RGBDImageFactory.cpp:40: Unsupported image format.

**Comment by kekeblom** [comment]
I haven't actually tried the open3d pipeline for a long time and it seems it has seen a few updates since I last used it. The convert script should resize the depth images to be the same size as RGB.

I just checked and it seems the conversion script had not been updated since the app was changed to save depth as png files. Just pushed a fix. Hope that fixes your issue.

**Comment by pangchunhei** [comment]
Hi, thanks for the update on the script, now it works without any errors. Thanks a lot
